language: csharp
solution: Asphalt.sln
install:
  - nuget restore Asphalt.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory runner
script:
  - xbuild /p:Configuration=Release Asphalt.sln
  - mono ./runner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Asphalt.Tests/bin/x64/Release/Asphalt.Tests.dll
after_script:
  - ./package.sh
mono:
  - latest
